joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_a2:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_a3:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_a4:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 1.11701
  joint_a5:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 1.11701
  joint_a6:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: true
    max_acceleration: 1.46608
