joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

eff_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &robot_joints
     - joint_a1
     - joint_a2
     - joint_a3
     - joint_a4
     - joint_a5
     - joint_a6
  gains: # Required because we're controlling an effort interface
      joint_a1: {p: 36.0, i: 0.41, d: 768.59}
      joint_a2: {p: 360.0, i: 4.11, d: 7866.0}
      joint_a3: {p: 36.0, i: 0.41, d: 768.59}
      joint_a4: {p: 7.2, i: 0.08, d: 157.32}
      joint_a5: {p: 6.0, i: 2.14, d: 4.2}
      joint_a6: {p: 10.0, i: 2.0, d: 0.0}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_a1: {trajectory: 0.2, goal: 0.2}
      joint_a2: {trajectory: 0.2, goal: 0.2}
      joint_a3: {trajectory: 0.2, goal: 0.2}
      joint_a4: {trajectory: 0.2, goal: 0.2}
      joint_a5: {trajectory: 0.2, goal: 0.2}
      joint_a6: {trajectory: 0.2, goal: 0.2}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *robot_joints

pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: *robot_joints
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_a1: {trajectory: 0.1, goal: 0.1}
      joint_a2: {trajectory: 0.1, goal: 0.1}
      joint_a3: {trajectory: 0.1, goal: 0.1}
      joint_a4: {trajectory: 0.1, goal: 0.1}
      joint_a5: {trajectory: 0.1, goal: 0.1}
      joint_a6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *robot_joints

inverse_controller:
  type: kuka_controllers/InverseDynamicController
  root_name: base_link
  tip_link: tool0

state_controller:
  type: kuka_controllers/KukaStateController
  root_name: base_link
  tip_link: tool0